# Generated by Django 2.2.17 on 2021-01-20 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projet', '0006_commentaire_date_publication'),
        ('utilisateur', '0008_utilisateur_img_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancementProjet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField(default=None)),
                ('commentaire', models.TextField()),
                ('date_financement', models.DateField()),
                ('financeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.Utilisateur')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet.Projet')),
            ],
        ),
    ]
