# Generated by Django 2.2.17 on 2020-12-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=30)),
                ('mail', models.CharField(max_length=60)),
                ('mdp_hache', models.CharField(max_length=100)),
                ('estValide', models.BooleanField()),
                ('date_creation', models.DateField()),
                ('karma_porteur', models.IntegerField()),
                ('karma_evaluateur', models.IntegerField()),
                ('karma_financeur', models.IntegerField()),
            ],
        ),
    ]
