# Generated by Django 2.2.17 on 2021-01-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='photo',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
