# Generated by Django 2.2.17 on 2021-01-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0002_utilisateur_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='photo',
            field=models.ImageField(default=None, upload_to='test'),
        ),
    ]
