# Generated by Django 2.2.17 on 2021-01-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0004_auto_20210113_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='test/'),
        ),
    ]
