# Generated by Django 2.2.17 on 2021-01-14 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utilisateur', '0006_remove_utilisateur_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='mdp_hache',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='pseudo',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='idUser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
