# Generated by Django 2.2.17 on 2021-01-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='cout_estime',
            field=models.FloatField(default=None),
        ),
    ]
