# Generated by Django 2.2.17 on 2021-01-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0002_projet_cout_estime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
