# Generated by Django 2.2.17 on 2021-01-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0003_auto_20210114_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/projet/'),
        ),
    ]
