# Generated by Django 2.2.17 on 2021-01-15 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0008_utilisateur_img_profil'),
        ('projet', '0003_auto_20210114_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/projet/'),
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField()),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet.Projet')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.Utilisateur')),
            ],
        ),
    ]
