# Generated by Django 2.2.17 on 2021-01-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0004_auto_20210115_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='moyenne_evaluation',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='projet',
            name='nbr_evaluation',
            field=models.IntegerField(default=0),
        ),
    ]
