# Generated by Django 2.2.17 on 2021-01-16 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0004_auto_20210115_1315'),
        ('projet', '0004_auto_20210115_1326'),
    ]

    operations = [
    ]
