# Generated by Django 2.2.17 on 2021-01-17 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0005_auto_20210117_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='date_publication',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
