# Generated by Django 2.2.17 on 2021-01-20 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0006_commentaire_date_publication'),
        ('projet', '0005_merge_20210116_1327'),
    ]

    operations = [
    ]
